### PR TITLE
Update index.html to include the link to nuget

### PR DESCRIPTION
**Pull request by abatishchev**
Also proper indentation of next block.

### CODE REVIEW

**Comment by abatishchev** [comment]
Any response, please?

**Comment by ChrisMissal** [comment]
Whoops, sorry

**Comment by ChrisMissal** [comment]
Thanks!

**Comment by abatishchev** [comment]
Awesome, thanks you too!

**Comment by abatishchev** [comment]
Hm, it didn't work as I'd expect:
wac

vs.

fa

Do you have any ideas?

**Comment by ChrisMissal** [comment]
Where does the ".cs" folder come from? That's an image sprite (sorry, didn't notice that when merging).

**Comment by abatishchev** [comment]
Oh, I see now. I thought it comes from GiHub pages built-in styles.

Here's the sprite image for WebApiContrib: http://webapicontrib.github.io/images/sprite_download.png
And here's for Fluent Assertions http://www.fluentassertions.com/images/sprite_download.png

**Pull request merged**
